[package]
name = "rusty_echo"
version = "0.1.0"
edition = "2024"

[dependencies]
<<<<<<< HEAD
tokio = { version = "1", features = ["full"] }
=======
tokio = { version = "1", features = ["full"] } 
>>>>>>> 21d1086 (made small changes)
